### ISSUE TITLE
nolockscreen_v2.suprx not working

### ISSUE THREAD

**Issue by nanashi89** [TheOfficialFloW/VitaTweaks#1]
[config.txt](https://github.com/TheOfficialFloW/VitaTweaks/files/2233855/config.txt)

Included is my current config file.

I followed the instructions on Wololo, and the lock screen STILL shows up.

What am I doing wrong?

**Comment by TheOfficialFloW** [comment]
Delete ux0:tai/config.txt if you want to use the config at ur0:
