### ISSUE TITLE
[Custom Warning] Feature Request: Add support for multiple messages and shuffle them ?!

### ISSUE THREAD

**Issue by Luro02** [TheOfficialFloW/VitaTweaks#11]
At first I had no clue what to put on the Custom Warning screen but after I found [this](https://www.brainyquote.com/lists/topics/top_10_computers_quotes) I can't really decide which one to use. So maybe you could add the possibility to add multiple messages and change them every time you boot your Vita (maybe via the cross sum of the date + time ?).
Thanks :)

**Comment by TheOfficialFloW** [comment]
I guess you can try to do it yourself, it‘s fun and not hard :)
