### ISSUE TITLE
Browser tweak dosent work

### ISSUE THREAD

**Issue by VitaBix** [TheOfficialFloW/VitaTweaks#15]
Yeah, I did everything but it still said it couldn't download...

**Comment by VitaBix** [comment]
Why did you close it?

**Comment by VitaBix** [comment]
Also im on 3.68, is that the reason?

**Comment by TheOfficialFloW** [comment]
Obviously because you didn't install it correctly and this is not the place to ask those questions.

**Comment by VitaBix** [comment]
> 
> 
> Obviously because you didn't install it correctly and **this is not the place to ask those questions.**

1.Well,i put it in the tai folder, editited the config file then reloaded it, yet it didn't work.
2.So where should I ask?

Also great job with vita shell and all the other applications (like h-encore), you changed the world of PS-VITA homebrew.
