### ISSUE TITLE
Battery draining too quickly on 3.60? (NoLockScreen v2)

### ISSUE THREAD

**Issue by DigiOhhh** [TheOfficialFloW/VitaTweaks#3]
Ever since I installed NoLockScreen my 3.60 Vita would not survive the night and be completely dead come the morning.
I couldn’t be sure it was actually the plugin’s fault, so after charging my Vita yesterday I commented it out of the config.txt file; this morning the system was still up and running.
Could you, or someone in possession of a Vita on 3.60, confirm of refuse this issue being related to NoLockScreen?

I also happen to have a 3.67 Vita, and the battery draining problem is non-existent there.

**Comment by TheOfficialFloW** [comment]
Update your gamesd driver.
