### ISSUE TITLE
Skip warning screen if no text

### ISSUE THREAD

**Issue by MegaPramuk** [TheOfficialFloW/VitaTweaks#5]
First of all, thanks for this particular plugin.
This is a plugin that I have been waiting for a very long time because I've always disliked the warning message (those don't serve a purpose for the most people). 
If it's doable, I'd love for this plugin to see this function.
If it is not (or it already does it under the hood), feel free to close this issue.

**Comment by TheOfficialFloW** [comment]
I tried but failed. Not worth my time tho. Sorry.
